{% set version = "75.8.0.20250225" %}

{% set python_min = python_min | default("3.9") %}

package:
  name: types-setuptools
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/t/types-setuptools/types_setuptools-{{ version }}.tar.gz
    sha256: 6038f7e983d55792a5f90d8fdbf5d4c186026214a16bb65dd6ae83c624ae9636
  - url: https://raw.githubusercontent.com/python/typeshed/main/LICENSE
    sha256: 295f8538c94ae5c3043301cf7cff1c852dab6a786a8ddee471e061b40d5ecabe

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - test -f $SP_DIR/pkg_resources-stubs/__init__.pyi
    - test -f $SP_DIR/setuptools-stubs/__init__.pyi
    - test -f $SP_DIR/distutils-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for setuptools
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
    - wolfv
