{% set version = "75.3.0.20241112" %}

package:
  name: types-setuptools
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/t/types-setuptools/types-setuptools-{{ version }}.tar.gz
    sha256: f9e1ebd17a56f606e16395c4ee4efa1cdc394b9a2a0ee898a624058b4b62ef8f
  - url: https://raw.githubusercontent.com/python/typeshed/main/LICENSE
    sha256: 295f8538c94ae5c3043301cf7cff1c852dab6a786a8ddee471e061b40d5ecabe

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8

test:
  commands:
    - test -f $SP_DIR/pkg_resources-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for setuptools
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
    - wolfv
