# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 75.8.2.20250305

package:
  name: types-setuptools
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/t/types-setuptools/types_setuptools-${{ version }}.tar.gz
    sha256: a987269b49488f21961a1d99aa8d281b611625883def6392a93855b31544e405
  - url: https://raw.githubusercontent.com/python/typeshed/main/LICENSE
    sha256: 295f8538c94ae5c3043301cf7cff1c852dab6a786a8ddee471e061b40d5ecabe

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
  run_constraints:
    # https://github.com/python/typeshed/blob/main/stubs/setuptools/METADATA.toml#L4C54-L4C62
    - setuptools >=71.1

tests:
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - test -f $SP_DIR/setuptools-stubs/__init__.pyi
      - test -f $SP_DIR/distutils-stubs/__init__.pyi
  - requirements:
      run:
        - mypy
        - python ${{ python_min }}.*
        - setuptools
    script:
      - pip check
      - mypy -p setuptools
      - mypy -p distutils

about:
  summary: Typing stubs for setuptools
  license: Apache-2.0 AND MIT
  license_file: LICENSE
  homepage: https://github.com/python/typeshed

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
    - wolfv
